import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs SSG app deploy to AWS amplify with CD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>This test the CD pipeline of the AWS amplify </p>
      </main>

      <footer className={styles.footer}>
        <p></p>
      </footer>
    </div>
  );
};

export default Home;
